/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame.Panel;

import electricitybillingsystem.Customer;
import electricitybillingsystem.Mail;
import electricitybillingsystem.Validation;
import java.awt.Color;
import javax.mail.MessagingException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author DELL
 */
public class AddCustomer extends javax.swing.JPanel {

    /**
     * Creates new form AddCustomer1
     */
    public AddCustomer() {
        initComponents();
         jPanelNotAllowed.setVisible(false);
        jPanelWrongEmail.setVisible(false);
        jPanelWrongID.setVisible(false);
        jPanelWrongMeterCode.setVisible(false);
        jPanelWrongPass.setVisible(false);
        jPanelWrongPhoneNo.setVisible(false);
        jPanelWrongRePass.setVisible(false);
        jPanelWrongURL.setVisible(false);
        jPanelWrongUserName.setVisible(false);
        jPanelWrongAddress.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxday = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldPhoneNo = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldMeterCode = new javax.swing.JTextField();
        jTextFieldAddress = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jPanelWrongUserName = new javax.swing.JPanel();
        jLabelWrongUserName1 = new javax.swing.JLabel();
        jPanelWrongPass = new javax.swing.JPanel();
        jLabelWrongPass1 = new javax.swing.JLabel();
        jPanelWrongPhoneNo = new javax.swing.JPanel();
        jLabelWrongPhoneNo1 = new javax.swing.JLabel();
        jPanelWrongEmail = new javax.swing.JPanel();
        jLabelWrongEmail1 = new javax.swing.JLabel();
        jTextFielduserName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxGender = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxGovernorate = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jPanelWrongMeterCode = new javax.swing.JPanel();
        jLabelID = new javax.swing.JLabel();
        jComboBoxRegion = new javax.swing.JComboBox<>();
        jPanelWrongID = new javax.swing.JPanel();
        jLabelWrongSalary1 = new javax.swing.JLabel();
        jPanelWrongRePass = new javax.swing.JPanel();
        jLabelWrongPass2 = new javax.swing.JLabel();
        jPanelNotAllowed = new javax.swing.JPanel();
        jLabelNotAllawed = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldURL = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPanelWrongURL = new javax.swing.JPanel();
        jLabelWrongAge2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanelWrongAddress = new javax.swing.JPanel();
        jLabelWrongAge3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboBoxyear = new javax.swing.JComboBox<>();
        jComboBoxmonth = new javax.swing.JComboBox<>();
        jTextFieldemail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jLabelSuccessOrFail = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanelProcess = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanelMail = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanelReset = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();

        setBackground(java.awt.SystemColor.controlDkShadow);

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Phone No.");

        jLabel11.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Date");

        jComboBoxday.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jComboBoxday.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32" }));

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("E-Mail");

        jLabel12.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Year");

        jTextFieldPhoneNo.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldPhoneNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPhoneNo.setBorder(null);

        jLabel17.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Meter Code");

        jTextFieldMeterCode.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldMeterCode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldMeterCode.setBorder(null);
        jTextFieldMeterCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMeterCodeActionPerformed(evt);
            }
        });

        jTextFieldAddress.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldAddress.setBorder(null);
        jTextFieldAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAddressActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("User Name");

        jPanelWrongUserName.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelWrongUserName1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelWrongUserName1.setForeground(java.awt.Color.red);
        jLabelWrongUserName1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelWrongUserName1.setText("Wrong User Name");

        javax.swing.GroupLayout jPanelWrongUserNameLayout = new javax.swing.GroupLayout(jPanelWrongUserName);
        jPanelWrongUserName.setLayout(jPanelWrongUserNameLayout);
        jPanelWrongUserNameLayout.setHorizontalGroup(
            jPanelWrongUserNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongUserNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWrongUserName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelWrongUserNameLayout.setVerticalGroup(
            jPanelWrongUserNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWrongUserNameLayout.createSequentialGroup()
                .addComponent(jLabelWrongUserName1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelWrongPass.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelWrongPass1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelWrongPass1.setForeground(java.awt.Color.red);
        jLabelWrongPass1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelWrongPass1.setText("Wrong Pass");

        javax.swing.GroupLayout jPanelWrongPassLayout = new javax.swing.GroupLayout(jPanelWrongPass);
        jPanelWrongPass.setLayout(jPanelWrongPassLayout);
        jPanelWrongPassLayout.setHorizontalGroup(
            jPanelWrongPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongPassLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWrongPass1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelWrongPassLayout.setVerticalGroup(
            jPanelWrongPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWrongPassLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelWrongPass1))
        );

        jPanelWrongPhoneNo.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelWrongPhoneNo1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelWrongPhoneNo1.setForeground(java.awt.Color.red);
        jLabelWrongPhoneNo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelWrongPhoneNo1.setText("Wrong Phone No");

        javax.swing.GroupLayout jPanelWrongPhoneNoLayout = new javax.swing.GroupLayout(jPanelWrongPhoneNo);
        jPanelWrongPhoneNo.setLayout(jPanelWrongPhoneNoLayout);
        jPanelWrongPhoneNoLayout.setHorizontalGroup(
            jPanelWrongPhoneNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongPhoneNoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWrongPhoneNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelWrongPhoneNoLayout.setVerticalGroup(
            jPanelWrongPhoneNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongPhoneNoLayout.createSequentialGroup()
                .addComponent(jLabelWrongPhoneNo1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelWrongEmail.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelWrongEmail1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelWrongEmail1.setForeground(java.awt.Color.red);
        jLabelWrongEmail1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelWrongEmail1.setText("Wrong E-Mail");

        javax.swing.GroupLayout jPanelWrongEmailLayout = new javax.swing.GroupLayout(jPanelWrongEmail);
        jPanelWrongEmail.setLayout(jPanelWrongEmailLayout);
        jPanelWrongEmailLayout.setHorizontalGroup(
            jPanelWrongEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongEmailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWrongEmail1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelWrongEmailLayout.setVerticalGroup(
            jPanelWrongEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWrongEmailLayout.createSequentialGroup()
                .addComponent(jLabelWrongEmail1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTextFielduserName.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFielduserName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFielduserName.setBorder(null);
        jTextFielduserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielduserNameActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Password");

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gender");

        jComboBoxGender.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jComboBoxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male","Famele" }));

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Governorate");

        jComboBoxGovernorate.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jComboBoxGovernorate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giza", "Cairo" }));
        jComboBoxGovernorate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGovernorateActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Region");

        jPanelWrongMeterCode.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelID.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelID.setForeground(java.awt.Color.red);
        jLabelID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelID.setText("Wrong Meter Code");

        javax.swing.GroupLayout jPanelWrongMeterCodeLayout = new javax.swing.GroupLayout(jPanelWrongMeterCode);
        jPanelWrongMeterCode.setLayout(jPanelWrongMeterCodeLayout);
        jPanelWrongMeterCodeLayout.setHorizontalGroup(
            jPanelWrongMeterCodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWrongMeterCodeLayout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelWrongMeterCodeLayout.setVerticalGroup(
            jPanelWrongMeterCodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, Short.MAX_VALUE)
        );

        jComboBoxRegion.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jComboBoxRegion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));

        jPanelWrongID.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelWrongSalary1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelWrongSalary1.setForeground(java.awt.Color.red);
        jLabelWrongSalary1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelWrongSalary1.setText("Wrong ID");

        javax.swing.GroupLayout jPanelWrongIDLayout = new javax.swing.GroupLayout(jPanelWrongID);
        jPanelWrongID.setLayout(jPanelWrongIDLayout);
        jPanelWrongIDLayout.setHorizontalGroup(
            jPanelWrongIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongIDLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelWrongSalary1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelWrongIDLayout.setVerticalGroup(
            jPanelWrongIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongIDLayout.createSequentialGroup()
                .addComponent(jLabelWrongSalary1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelWrongRePass.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelWrongPass2.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelWrongPass2.setForeground(java.awt.Color.red);
        jLabelWrongPass2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelWrongPass2.setText("Wrong RePass");

        javax.swing.GroupLayout jPanelWrongRePassLayout = new javax.swing.GroupLayout(jPanelWrongRePass);
        jPanelWrongRePass.setLayout(jPanelWrongRePassLayout);
        jPanelWrongRePassLayout.setHorizontalGroup(
            jPanelWrongRePassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongRePassLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWrongPass2, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
        );
        jPanelWrongRePassLayout.setVerticalGroup(
            jPanelWrongRePassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongRePassLayout.createSequentialGroup()
                .addComponent(jLabelWrongPass2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelNotAllowed.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelNotAllawed.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelNotAllawed.setForeground(java.awt.Color.red);
        jLabelNotAllawed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelNotAllawed.setText("Not Allowed");

        javax.swing.GroupLayout jPanelNotAllowedLayout = new javax.swing.GroupLayout(jPanelNotAllowed);
        jPanelNotAllowed.setLayout(jPanelNotAllowedLayout);
        jPanelNotAllowedLayout.setHorizontalGroup(
            jPanelNotAllowedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNotAllowedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNotAllawed, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelNotAllowedLayout.setVerticalGroup(
            jPanelNotAllowedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNotAllowedLayout.createSequentialGroup()
                .addComponent(jLabelNotAllawed)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Upload your Apartment's URL");

        jTextFieldURL.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldURL.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldURL.setBorder(null);
        jTextFieldURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldURLActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Address");

        jLabel16.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Re Password");

        jPasswordField1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jPasswordField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField1.setBorder(null);

        jPasswordField2.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jPasswordField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField2.setBorder(null);

        jPanelWrongURL.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelWrongAge2.setBackground(java.awt.SystemColor.controlDkShadow);
        jLabelWrongAge2.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelWrongAge2.setForeground(java.awt.Color.red);
        jLabelWrongAge2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelWrongAge2.setText("Wrong URL");

        javax.swing.GroupLayout jPanelWrongURLLayout = new javax.swing.GroupLayout(jPanelWrongURL);
        jPanelWrongURL.setLayout(jPanelWrongURLLayout);
        jPanelWrongURLLayout.setHorizontalGroup(
            jPanelWrongURLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWrongURLLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelWrongAge2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelWrongURLLayout.setVerticalGroup(
            jPanelWrongURLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWrongURLLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelWrongAge2))
        );

        jLabel13.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Month");

        jPanelWrongAddress.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelWrongAge3.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelWrongAge3.setForeground(java.awt.Color.red);
        jLabelWrongAge3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelWrongAge3.setText("Wrong Address");

        javax.swing.GroupLayout jPanelWrongAddressLayout = new javax.swing.GroupLayout(jPanelWrongAddress);
        jPanelWrongAddress.setLayout(jPanelWrongAddressLayout);
        jPanelWrongAddressLayout.setHorizontalGroup(
            jPanelWrongAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongAddressLayout.createSequentialGroup()
                .addComponent(jLabelWrongAge3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelWrongAddressLayout.setVerticalGroup(
            jPanelWrongAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongAddressLayout.createSequentialGroup()
                .addComponent(jLabelWrongAge3)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Day");

        jComboBoxyear.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jComboBoxyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "18" , "19" , "21" , "22" }));
        jComboBoxyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxyearActionPerformed(evt);
            }
        });

        jComboBoxmonth.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jComboBoxmonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1","2","3","4","5","6","7","8","9","10","11","12" }));

        jTextFieldemail.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldemail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldemail.setBorder(null);
        jTextFieldemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldemailActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID Customer");

        jTextFieldID.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldID.setBorder(null);
        jTextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDActionPerformed(evt);
            }
        });

        jLabelSuccessOrFail.setBackground(java.awt.SystemColor.controlDkShadow);
        jLabelSuccessOrFail.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabelSuccessOrFail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSuccessOrFail.setText("Add Customer ... !");

        jLabel21.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Reset");

        jLabel20.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Process");

        jLabel22.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Process & Send Mail");

        jPanelProcess.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Process_96px.png"))); // NOI18N
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel23MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel23MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelProcessLayout = new javax.swing.GroupLayout(jPanelProcess);
        jPanelProcess.setLayout(jPanelProcessLayout);
        jPanelProcessLayout.setHorizontalGroup(
            jPanelProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProcessLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel23)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelProcessLayout.setVerticalGroup(
            jPanelProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelMail.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Send_Email_96px.png"))); // NOI18N
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel24MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel24MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelMailLayout = new javax.swing.GroupLayout(jPanelMail);
        jPanelMail.setLayout(jPanelMailLayout);
        jPanelMailLayout.setHorizontalGroup(
            jPanelMailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMailLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel24)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelMailLayout.setVerticalGroup(
            jPanelMailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMailLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel24))
        );

        jPanelReset.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Reset_96px.png"))); // NOI18N
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel25MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel25MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelResetLayout = new javax.swing.GroupLayout(jPanelReset);
        jPanelReset.setLayout(jPanelResetLayout);
        jPanelResetLayout.setHorizontalGroup(
            jPanelResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResetLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel25)
                .addGap(0, 0, 0))
        );
        jPanelResetLayout.setVerticalGroup(
            jPanelResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxGovernorate, 0, 193, Short.MAX_VALUE)
                                    .addComponent(jComboBoxGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(115, 115, 115)
                                .addComponent(jLabel7)
                                .addGap(32, 32, 32)
                                .addComponent(jComboBoxRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldMeterCode, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFielduserName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                                            .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextFieldemail, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanelWrongRePass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanelWrongEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanelWrongUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanelWrongID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanelWrongPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanelWrongMeterCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jPanelNotAllowed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanelWrongPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabelSuccessOrFail, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(99, 99, 99)
                        .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelWrongAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12)
                        .addComponent(jTextFieldURL, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(186, 186, 186))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelWrongURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(71, 71, 71)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(112, 112, 112)
                                            .addComponent(jComboBoxyear, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(121, 121, 121)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(20, 20, 20)
                                            .addComponent(jComboBoxmonth, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(20, 20, 20))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addGap(52, 52, 52)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jComboBoxday, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(26, 26, 26)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(344, 344, 344))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(56, 56, 56)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(83, 83, 83)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(34, 34, 34)
                                    .addComponent(jPanelMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(60, 60, 60)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanelProcess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(60, 60, 60)
                                    .addComponent(jPanelReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(92, 92, 92)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelSuccessOrFail)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanelWrongID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanelWrongPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldMeterCode, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanelWrongMeterCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelNotAllowed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldemail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanelWrongEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFielduserName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanelWrongUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelWrongPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelWrongRePass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxGovernorate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanelWrongAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxyear, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxmonth, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxday, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldURL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5))
                    .addComponent(jPanelWrongURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelProcess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldMeterCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMeterCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMeterCodeActionPerformed

    private void jTextFieldAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAddressActionPerformed

    private void jTextFielduserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielduserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielduserNameActionPerformed

    private void jComboBoxGovernorateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGovernorateActionPerformed
        // TODO add your handling code here:
        if(jComboBoxGovernorate.getSelectedItem().equals("Giza")){
            jComboBoxRegion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Warraq" ,"Agouza","Al Salam","Dokii","El Haram","Imbaba","Zamalek" }));

        }
        else
        jComboBoxRegion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Old Misr","Rawd Al-Faraj","Nasr City","Downtown Cairo","Ahmed Helmy","Sakakini","Peace","Khalafawi" }));

    }//GEN-LAST:event_jComboBoxGovernorateActionPerformed

    private void jTextFieldURLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldURLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldURLActionPerformed

    private void jComboBoxyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxyearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxyearActionPerformed

    private void jTextFieldemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldemailActionPerformed

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDActionPerformed
public void resetPanel()
    {
        jTextFieldID.setText("");
        jTextFieldMeterCode.setText("");
        jPasswordField1.setText("");
        jPasswordField2.setText("");
        jTextFieldAddress.setText("");
        jTextFieldPhoneNo.setText("");
        jTextFieldURL.setText("");
        jTextFieldemail.setText("");
        jTextFielduserName.setText("");
        jComboBoxGovernorate.setSelectedIndex(0);
        jComboBoxGender.setSelectedIndex(0);
        jComboBoxday.setSelectedIndex(0);
        jComboBoxmonth.setSelectedIndex(0);
        jComboBoxyear.setSelectedIndex(0);
        jComboBoxRegion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        
        
        jPanelNotAllowed.setVisible(false);
        jPanelWrongEmail.setVisible(false);
        jPanelWrongID.setVisible(false);
        jPanelWrongMeterCode.setVisible(false);
        jPanelWrongPass.setVisible(false);
        jPanelWrongPhoneNo.setVisible(false);
        jPanelWrongRePass.setVisible(false);
        jPanelWrongURL.setVisible(false);
        jPanelWrongUserName.setVisible(false);
        jPanelWrongAddress.setVisible(false);

    }
    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        // TODO add your handling code here:
        jPanelNotAllowed.setVisible(false);
        jPanelWrongEmail.setVisible(false);
        jPanelWrongMeterCode.setVisible(false);
        jPanelWrongID.setVisible(false);
        jPanelWrongPass.setVisible(false);
        jPanelWrongPhoneNo.setVisible(false);
        jPanelWrongRePass.setVisible(false);
        jPanelWrongURL.setVisible(false);
        jPanelWrongUserName.setVisible(false);
        jPanelWrongAddress.setVisible(false);
        
        if( !jTextFieldMeterCode.getText().equals("") && !jTextFieldMeterCode.getText().equals("") && 
                !jTextFieldPhoneNo.getText().equals("") && !jTextFieldemail.getText().equals("") && !jTextFieldID.getText().equals("")
                && !jPasswordField1.getText().equals("") && !jPasswordField2.getText().equals("")
                && !jTextFieldURL.getText().equals("") && !jTextFielduserName.getText().equals("") )
        {
            //All Check ...
            Validation v = new Validation();
            if(v.checkID(jTextFieldID.getText())){
                    if(v.checkName(jTextFielduserName.getText())){
                        if(v.checkPass(jPasswordField1.getText())){
                            if(v.checkPass(jPasswordField2.getText())){
                                if(v.checkEmail(jTextFieldemail.getText())){
                                        if(v.checkPhoneNo(jTextFieldPhoneNo.getText())){
                                            if(v.checkID(jTextFieldMeterCode.getText())){
                                                    if(v.checkAddress(jTextFieldAddress.getText())){
                                                        if(v.checkURL(jTextFieldURL.getText())){
                                                    
                                                            // End Check :)
                                                            // Start Add
                                                                // Name & ID & PhoneNo & Email &Source & distination & t.ID_Train & ID_Ticket
                                                                Customer t = new Customer();
                                                                if(!t.Dublicate(Integer.parseInt(jTextFieldMeterCode.getText()))){
                                                                    t.setID(Integer.parseInt(jTextFieldID.getText()));
                                                                    t.setPhoneNo(jTextFieldPhoneNo.getText());
                                                                    t.setEmail(jTextFieldemail.getText());
                                                                    t.setMeterCode(Integer.parseInt(jTextFieldMeterCode.getText()));
                                                                    t.setUserName(jTextFielduserName.getText());
                                                                    t.setGender(jComboBoxGender.getSelectedItem().toString());
                                                                    t.setGovernorate(jComboBoxGovernorate.getSelectedItem().toString());
                                                                    t.setRegion(jComboBoxRegion.getSelectedItem().toString());
                                                                    t.setApartment(jTextFieldURL.getText());
                                                                    String date = jComboBoxyear.getSelectedItem().toString()+"#"+jComboBoxmonth.getSelectedItem().toString()+"#"+jComboBoxday.getSelectedItem().toString()
                                                                    +"#";
                                                                    t.setDate(date);
                                                                    t.setAddress(jTextFieldAddress.getText());
                                                                    if(jPasswordField1.getText().equals(jPasswordField2.getText())){
                                                                           t.setPassword(jPasswordField1.getText());
                                                                            if(t.addCustomer()){
                                                                                jLabelSuccessOrFail.setText("Added Successufully ... ! :) ");
                                                                                resetPanel();
                                                                            }
                                                                            else
                                                                            jLabelSuccessOrFail.setText("Failed To Insert ... ! (:");
                                                                            
                                                                        }
                                                                        else{
                                                                        jLabelSuccessOrFail.setText("Password & Repassword not Similar ... ! :("); 
                                                                        JOptionPane.showMessageDialog(jLabel23, "Not valid Password & Repassword not Similar Try Again :(");
                                                                        jPanelWrongPass.setVisible(true); jPanelWrongRePass.setVisible(true);
                                                                    }
                                                                    //End Start & start elses for Check
                                                            }
                                                               else{
                                                                    jLabelSuccessOrFail.setText("Not Allowed New Meter Code Customer :(");
                                                                    jPanelNotAllowed.setVisible(true);
                                                                    JOptionPane.showMessageDialog(jLabel23, "Not Allowed Meter Code Customer , Meter Code Customer is Reserved...!\n Try Again :(");
                                                                }
                                                        }
                                                        else{
                                                            JOptionPane.showMessageDialog(jLabel23, "Not valid Input for URL Try Again :(");
                                                            jPanelWrongURL.setVisible(true);
                                                        }
                                                }
                                                    else{
                                                        JOptionPane.showMessageDialog(jLabel23, "Not valid Input for Address Try Again :(");
                                                        jPanelWrongAddress.setVisible(true);
                                                    }
                                            
                                        }
                                        else{
                                            JOptionPane.showMessageDialog(jLabel23, "Not valid Meter Code Try Again :(\nHint: Meter Code Length should more than 4 .. ;)");
                                            jPanelWrongMeterCode.setVisible(true);
                                        }
                                        
                                        }
                                        else{
                                            JOptionPane.showMessageDialog(jLabel23, "Not valid Phone No Try Again :(\nHint: Phone No should  equal 11 numbers if it mobile\n or more than 8 with Code of Governorate if it Tel  .. ;)");
                                            jPanelWrongPhoneNo.setVisible(true);
                                        }
                                    
                                }
                                else{
                                    JOptionPane.showMessageDialog(jLabel23, "Not valid Input for Email Try Again :(");
                                    jPanelWrongEmail.setVisible(true);
                                }
                            }
                            else{
                                JOptionPane.showMessageDialog(jLabel23, "Not valid RePassword length ,Should it Length\nis more than 6 OR Password has (*,/,=,+,...)\n                    Try Again :(");
                                jPanelWrongRePass.setVisible(true);
                            }
                        }
                        else{
                            JOptionPane.showMessageDialog(jLabel23, "Not valid Password length ,Should it Length\nis more than 6 OR Password has (*,/,=,+,...)\n                    Try Again :(");
                            jPanelWrongPass.setVisible(true);
                        }
                }
                    else{
                        JOptionPane.showMessageDialog(jLabel23, "Not valid User Name Try Again :(");
                        jPanelWrongUserName.setVisible(true);
                    }
                
            }
            else{
                JOptionPane.showMessageDialog(jLabel23, "Not valid ID Try Again :(\nHint: ID Length should more than 4 .. ;)");
                jPanelWrongID.setVisible(true);
            }
        }
        else
        jLabelSuccessOrFail.setText("Missing Required Fields ... ! Please Fill All Fields (:");
    }//GEN-LAST:event_jLabel23MouseClicked
private void setColor(JPanel p)
    {
        p.setBackground(new java.awt.Color(0,64,128));
    }
    private void getColor(JPanel p)
    {
        p.setBackground(new java.awt.Color(105,105,105));
    }
    private void jLabel23MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseEntered
        // TODO add your handling code here:
        setColor(jPanelProcess);
    }//GEN-LAST:event_jLabel23MouseEntered

    private void jLabel23MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseExited
        // TODO add your handling code here:
        getColor(jPanelProcess);
    }//GEN-LAST:event_jLabel23MouseExited

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        // TODO add your handling code here:

        jPanelNotAllowed.setVisible(false);
        jPanelWrongEmail.setVisible(false);
        jPanelWrongID.setVisible(false);
        jPanelWrongMeterCode.setVisible(false);
        jPanelWrongPass.setVisible(false);
        jPanelWrongPhoneNo.setVisible(false);
        jPanelWrongRePass.setVisible(false);
        jPanelWrongURL.setVisible(false);
        jPanelWrongUserName.setVisible(false);
        jPanelWrongAddress.setVisible(false);
        
        if( !jTextFieldMeterCode.getText().equals("") && !jTextFieldMeterCode.getText().equals("") && 
                !jTextFieldPhoneNo.getText().equals("") && !jTextFieldemail.getText().equals("") && !jTextFieldID.getText().equals("")
                && !jPasswordField1.getText().equals("") && !jPasswordField2.getText().equals("") 
                && !jTextFieldURL.getText().equals("") && !jTextFielduserName.getText().equals("") )
        
        {
            //All Check ...
            Validation v = new Validation();
            if(v.checkID(jTextFieldID.getText())){
                    if(v.checkName(jTextFielduserName.getText())){
                        if(v.checkPass(jPasswordField1.getText())){
                            if(v.checkPass(jPasswordField2.getText())){
                                if(v.checkEmail(jTextFieldemail.getText())){
                                        if(v.checkPhoneNo(jTextFieldPhoneNo.getText())){
                                            if(v.checkID(jTextFieldMeterCode.getText())){
                                                    if(v.checkAddress(jTextFieldAddress.getText())){
                                                        if(v.checkURL(jTextFieldURL.getText())){
                                                            // End Check :)
                                                            // Start Add
                                                            //    public Mail(String To , String Cc , String subject , String body)
                                                            // Name & ID & PhoneNo & Email &Source & distination & t.ID_Train & ID_Ticket
                                                                Customer t = new Customer();
                                                                if(!t.Dublicate(Integer.parseInt(jTextFieldMeterCode.getText()))){
                                                                    t.setID(Integer.parseInt(jTextFieldID.getText()));
                                                                    t.setPhoneNo(jTextFieldPhoneNo.getText());
                                                                    t.setEmail(jTextFieldemail.getText());
                                                                    t.setMeterCode(Integer.parseInt(jTextFieldMeterCode.getText()));
                                                                    t.setUserName(jTextFielduserName.getText());
                                                                    t.setGender(jComboBoxGender.getSelectedItem().toString());
                                                                    t.setGovernorate(jComboBoxGovernorate.getSelectedItem().toString());
                                                                    t.setRegion(jComboBoxRegion.getSelectedItem().toString());
                                                                    t.setApartment(jTextFieldURL.getText());
                                                                    String date = jComboBoxyear.getSelectedItem().toString()+"#"+jComboBoxmonth.getSelectedItem().toString()+"#"+jComboBoxday.getSelectedItem().toString()
                                                                    +"#";
                                                                    t.setDate(date);
                                                                    t.setAddress(jTextFieldAddress.getText());
                                                                    if(jPasswordField1.getText().equals(jPasswordField2.getText())){
                                                                            t.setPassword(jPasswordField1.getText());
                                                                            //Start Mail
                                                                            Mail m = new Mail();
                                                                            m.setToEmail(jTextFieldemail.getText());
                                                                            m.setCcEmail("");
                                                                            m.setSubject("Company Billing System");
                                                                            m.setEmailbody("company Billing System \nYour Meter Code is  ("+jTextFieldMeterCode.getText()+")  Your ID is ("+jTextFieldID.getText()
                                                                                +"$ \nAnd Date is :  "+jComboBoxyear.getSelectedItem().toString()+"/"+jComboBoxmonth.getSelectedItem().toString()+"/"+jComboBoxday.getSelectedItem().toString()
                                                                                +"\n");
                                                                            try {
                                                                                //jButton1ActionPerformed(evt);
                                                                                m.generateAndSentMessage();
                                                                                jLabelSuccessOrFail.setText("Your message has been sent & Added Successufully  ...! :)");
                                                                                resetPanel();
                                                                            } catch (MessagingException ex) {
                                                                                jLabelSuccessOrFail.setText("Your Message hasn't been delivered & Failed To Insert ... ! :(");
                                                                            }
                                                                            //End Mail
                                                                            if(t.addCustomer()){
                                                                                jLabelSuccessOrFail.setText("Added Successufully ... ! :) ");
                                                                                resetPanel();
                                                                            }
                                                                            else
                                                                            jLabelSuccessOrFail.setText("Failed To Insert ... ! (:");
                                                                
                                                                    }
                                                                    else{
                                                                    jLabelSuccessOrFail.setText("Password & Repassword not Similar ... ! :("); 
                                                                    JOptionPane.showMessageDialog(jLabel24, "Not valid Password & Repassword not Similar Try Again :(");
                                                                    jPanelWrongPass.setVisible(true); jPanelWrongRePass.setVisible(true);
                                                                }
                                                                     //End Start & start elses for Check
                                                                }
                                                            else{
                                                                    jLabelSuccessOrFail.setText("Not Allowed New Meter Code Customer :(");
                                                                    jPanelNotAllowed.setVisible(true);
                                                                    JOptionPane.showMessageDialog(jLabel24, "Not Allowed Meter Code Customer , Meter Codes Customer is Reserved...!\n Try Again :(");
                                                                }    
                                                        }
                                                        else{
                                                            JOptionPane.showMessageDialog(jLabel24, "Not valid Input for URL Try Again :(");
                                                            jPanelWrongURL.setVisible(true);
                                                        }
                                                }
                                                    else{
                                                        JOptionPane.showMessageDialog(jLabel24, "Not valid Input for Address Try Again :(");
                                                        jPanelWrongAddress.setVisible(true);
                                                    }
                                            
                                        }
                                        else{
                                            JOptionPane.showMessageDialog(jLabel24, "Not valid Meter Code Try Again :(\nHint: Meter Code Length should more than 4 .. ;)");
                                            jPanelWrongMeterCode.setVisible(true);
                                        }
                                        
                                        }
                                        else{
                                            JOptionPane.showMessageDialog(jLabel24, "Not valid Phone No Try Again :(\nHint: Phone No should  equal 11 numbers if it mobile\n or more than 8 with Code of Governorate if it Tel  .. ;)");
                                            jPanelWrongPhoneNo.setVisible(true);
                                        }
                                   
                                }
                                else{
                                    JOptionPane.showMessageDialog(jLabel24, "Not valid Input for Email Try Again :(");
                                    jPanelWrongEmail.setVisible(true);
                                }
                            }
                            else{
                                JOptionPane.showMessageDialog(jLabel24, "Not valid RePassword length ,Should it Length\nis more than 6 OR Password has (*,/,=,+,...)\n                    Try Again :(");
                                jPanelWrongRePass.setVisible(true);
                            }
                        }
                        else{
                            JOptionPane.showMessageDialog(jLabel24, "Not valid Password length ,Should it Length\nis more than 6 OR Password has (*,/,=,+,...)\n                    Try Again :(");
                            jPanelWrongPass.setVisible(true);
                        }
                }
                    else{
                        JOptionPane.showMessageDialog(jLabel24, "Not valid User Name Try Again :(");
                        jPanelWrongUserName.setVisible(true);
                    }
                
            }
            else{
                JOptionPane.showMessageDialog(jLabel24, "Not valid ID Try Again :(\nHint: ID Length should more than 4 .. ;)");
                jPanelWrongID.setVisible(true);
            }
        }
        else
        jLabelSuccessOrFail.setText("Missing required Fields ... !  Please, complete them before submit ...! :(");
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jLabel24MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseEntered
        // TODO add your handling code here:
        setColor(jPanelMail);
    }//GEN-LAST:event_jLabel24MouseEntered

    private void jLabel24MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseExited
        // TODO add your handling code here:
        getColor(jPanelMail);
    }//GEN-LAST:event_jLabel24MouseExited

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        // TODO add your handling code here:
        resetPanel();
        jLabelSuccessOrFail.setText("Add Customer ... !");
    }//GEN-LAST:event_jLabel25MouseClicked

    private void jLabel25MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseEntered
        // TODO add your handling code here:
        setColor(jPanelReset);
    }//GEN-LAST:event_jLabel25MouseEntered

    private void jLabel25MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseExited
        // TODO add your handling code here:
        getColor(jPanelReset);
    }//GEN-LAST:event_jLabel25MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxGender;
    private javax.swing.JComboBox<String> jComboBoxGovernorate;
    private javax.swing.JComboBox<String> jComboBoxRegion;
    private javax.swing.JComboBox<String> jComboBoxday;
    private javax.swing.JComboBox<String> jComboBoxmonth;
    private javax.swing.JComboBox<String> jComboBoxyear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelNotAllawed;
    private javax.swing.JLabel jLabelSuccessOrFail;
    private javax.swing.JLabel jLabelWrongAge2;
    private javax.swing.JLabel jLabelWrongAge3;
    private javax.swing.JLabel jLabelWrongEmail1;
    private javax.swing.JLabel jLabelWrongPass1;
    private javax.swing.JLabel jLabelWrongPass2;
    private javax.swing.JLabel jLabelWrongPhoneNo1;
    private javax.swing.JLabel jLabelWrongSalary1;
    private javax.swing.JLabel jLabelWrongUserName1;
    private javax.swing.JPanel jPanelMail;
    private javax.swing.JPanel jPanelNotAllowed;
    private javax.swing.JPanel jPanelProcess;
    private javax.swing.JPanel jPanelReset;
    private javax.swing.JPanel jPanelWrongAddress;
    private javax.swing.JPanel jPanelWrongEmail;
    private javax.swing.JPanel jPanelWrongID;
    private javax.swing.JPanel jPanelWrongMeterCode;
    private javax.swing.JPanel jPanelWrongPass;
    private javax.swing.JPanel jPanelWrongPhoneNo;
    private javax.swing.JPanel jPanelWrongRePass;
    private javax.swing.JPanel jPanelWrongURL;
    private javax.swing.JPanel jPanelWrongUserName;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldMeterCode;
    private javax.swing.JTextField jTextFieldPhoneNo;
    private javax.swing.JTextField jTextFieldURL;
    private javax.swing.JTextField jTextFieldemail;
    private javax.swing.JTextField jTextFielduserName;
    // End of variables declaration//GEN-END:variables
}
