/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame.Panel;

import electricitybillingsystem.Customer;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class ListAllCustomer extends javax.swing.JPanel {

    /**
     * Creates new form ListAllCustomer
     */
    public ListAllCustomer() {
        initComponents();
        //AddRowToJtable();
    }
    public void AddRowToJtable()
    {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Object rowData[]=new Object[11];
        Customer x = new Customer();
        ArrayList<Customer>cutms = x.ListAllCustomer();
        
        for( Customer c : cutms)
        {
            rowData[0]=c.getMeterCode();
            rowData[1]=c.getID();
            rowData[2]=c.getUserName();
            rowData[3]=c.getEmail();
            rowData[4]=c.getPassword();
            rowData[5]=c.getPhoneNo();
            rowData[6]=c.getApartment();
            rowData[7]=c.getGovernorate();
            rowData[8]=c.getRegion();
            rowData[9]=c.getAddress();
            String []seprated = c.getDate().split("#");
            rowData[10]=(Integer.parseInt(seprated[0])+2000)+"/"+seprated[1]+"/"+seprated[2];
            model.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(java.awt.SystemColor.activeCaptionText);

        jTable1.setBackground(java.awt.SystemColor.controlDkShadow);
        jTable1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Meter Code", "ID", "User Name", "E-Mail", "Password", "Phone No.", "Apartment", "Governorate", "Region", "Address", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("Meter Code");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("ID");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("User Name");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("E-Mail");
            jTable1.getColumnModel().getColumn(4).setHeaderValue("Password");
            jTable1.getColumnModel().getColumn(5).setHeaderValue("Phone No.");
            jTable1.getColumnModel().getColumn(6).setHeaderValue("Apartment");
            jTable1.getColumnModel().getColumn(7).setHeaderValue("Governorate");
            jTable1.getColumnModel().getColumn(8).setHeaderValue("Region");
            jTable1.getColumnModel().getColumn(9).setHeaderValue("Address");
            jTable1.getColumnModel().getColumn(10).setHeaderValue("Date");
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
