/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame.Panel;

import electricitybillingsystem.Customer;
import electricitybillingsystem.Validation;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author DELL
 */
public class UpdateCustomer extends javax.swing.JPanel {

    /**
     * Creates new form UpdateCustomer1
     */
    public UpdateCustomer() {
        initComponents();
        jPanelSearchKey1.setVisible(false);
        jPanelEmail1.setVisible(false);
        jPanelID1.setVisible(false);
        jPanelPass1.setVisible(false);
        jPanelUserName1.setVisible(false);
        jPanelUrl1.setVisible(false);
        jPanelAddress1.setVisible(false);
        jPanelMeterCode1.setVisible(false);
        jPanelNotAllowed1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSuccessOrFail = new javax.swing.JLabel();
        jTextFieldMeterCode1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jComboBoxyear1 = new javax.swing.JComboBox<>();
        jComboBoxmonth1 = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jComboBoxday1 = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextFieldPass1 = new javax.swing.JTextField();
        jTextFieldAddress1 = new javax.swing.JTextField();
        jTextFieldURL1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextFieldUserName1 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jComboBoxGovern1 = new javax.swing.JComboBox<>();
        jTextFieldID1 = new javax.swing.JTextField();
        jComboBoxRagion1 = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jTextFieldSearchKey1 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jTextFieldEmail1 = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        jLabelWrongURL2 = new javax.swing.JLabel();
        jPanelMeterCode1 = new javax.swing.JPanel();
        jLabelWrongMeterCode1 = new javax.swing.JLabel();
        jPanelID1 = new javax.swing.JPanel();
        jLabelWrongID2 = new javax.swing.JLabel();
        jPanelAddress1 = new javax.swing.JPanel();
        jLabelWrongAddress1 = new javax.swing.JLabel();
        jPanelEmail1 = new javax.swing.JPanel();
        jLabelWrongEmail1 = new javax.swing.JLabel();
        jPanelUserName1 = new javax.swing.JPanel();
        jLabelWrongUserName1 = new javax.swing.JLabel();
        jPanelUrl1 = new javax.swing.JPanel();
        jLabelWrongURL3 = new javax.swing.JLabel();
        jPanelPass1 = new javax.swing.JPanel();
        jLabelWrongPass1 = new javax.swing.JLabel();
        jPanelNotAllowed1 = new javax.swing.JPanel();
        jLabelWrongID3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelReset = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelSearch = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jPanelSearchKey1 = new javax.swing.JPanel();
        jLabel55454 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();

        setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelSuccessOrFail.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabelSuccessOrFail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSuccessOrFail.setText("Search Info of Customer ... !");

        jTextFieldMeterCode1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldMeterCode1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldMeterCode1.setBorder(null);
        jTextFieldMeterCode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMeterCode1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Meter Code");

        jLabel19.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Month");

        jLabel20.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Day");

        jComboBoxyear1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jComboBoxyear1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "18" , "19" , "21" , "22" }));
        jComboBoxyear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxyear1ActionPerformed(evt);
            }
        });

        jComboBoxmonth1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jComboBoxmonth1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1","2","3","4","5","6","7","8","9","10","11","12" }));

        jLabel21.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Date");

        jComboBoxday1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jComboBoxday1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32" }));

        jLabel22.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Year");

        jLabel23.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("ID Customer");

        jLabel24.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Governorate");

        jLabel25.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Address");

        jLabel26.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Ragion");

        jTextFieldPass1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldPass1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPass1.setBorder(null);
        jTextFieldPass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPass1ActionPerformed(evt);
            }
        });

        jTextFieldAddress1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldAddress1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldAddress1.setBorder(null);
        jTextFieldAddress1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAddress1ActionPerformed(evt);
            }
        });

        jTextFieldURL1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldURL1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldURL1.setBorder(null);
        jTextFieldURL1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldURL1ActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("UserName");

        jTextFieldUserName1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldUserName1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldUserName1.setBorder(null);
        jTextFieldUserName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUserName1ActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Apartment's URL");

        jComboBoxGovern1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jComboBoxGovern1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giza","Cairo" }));
        jComboBoxGovern1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGovern1ActionPerformed(evt);
            }
        });

        jTextFieldID1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldID1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldID1.setBorder(null);

        jComboBoxRagion1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jComboBoxRagion1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        jComboBoxRagion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxRagion1ActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Password");

        jLabel31.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("E-Mail");

        jTextFieldSearchKey1.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jTextFieldSearchKey1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSearchKey1.setBorder(null);

        jLabel32.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Meter Code");

        jTextFieldEmail1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldEmail1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldEmail1.setBorder(null);
        jTextFieldEmail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmail1ActionPerformed(evt);
            }
        });

        jPanelMeterCode1.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelWrongMeterCode1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelWrongMeterCode1.setForeground(java.awt.Color.red);
        jLabelWrongMeterCode1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelWrongMeterCode1.setText("Wrong Meter Code");

        javax.swing.GroupLayout jPanelMeterCode1Layout = new javax.swing.GroupLayout(jPanelMeterCode1);
        jPanelMeterCode1.setLayout(jPanelMeterCode1Layout);
        jPanelMeterCode1Layout.setHorizontalGroup(
            jPanelMeterCode1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMeterCode1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWrongMeterCode1, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
        );
        jPanelMeterCode1Layout.setVerticalGroup(
            jPanelMeterCode1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMeterCode1Layout.createSequentialGroup()
                .addComponent(jLabelWrongMeterCode1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelID1.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelWrongID2.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelWrongID2.setForeground(java.awt.Color.red);
        jLabelWrongID2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelWrongID2.setText("Wrong ID");

        javax.swing.GroupLayout jPanelID1Layout = new javax.swing.GroupLayout(jPanelID1);
        jPanelID1.setLayout(jPanelID1Layout);
        jPanelID1Layout.setHorizontalGroup(
            jPanelID1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelID1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWrongID2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelID1Layout.setVerticalGroup(
            jPanelID1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelID1Layout.createSequentialGroup()
                .addComponent(jLabelWrongID2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelAddress1.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelWrongAddress1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelWrongAddress1.setForeground(java.awt.Color.red);
        jLabelWrongAddress1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelWrongAddress1.setText("Wrong Address");

        javax.swing.GroupLayout jPanelAddress1Layout = new javax.swing.GroupLayout(jPanelAddress1);
        jPanelAddress1.setLayout(jPanelAddress1Layout);
        jPanelAddress1Layout.setHorizontalGroup(
            jPanelAddress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddress1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWrongAddress1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAddress1Layout.setVerticalGroup(
            jPanelAddress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddress1Layout.createSequentialGroup()
                .addComponent(jLabelWrongAddress1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelEmail1.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelWrongEmail1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelWrongEmail1.setForeground(java.awt.Color.red);
        jLabelWrongEmail1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelWrongEmail1.setText("Wrong E-Mail");

        javax.swing.GroupLayout jPanelEmail1Layout = new javax.swing.GroupLayout(jPanelEmail1);
        jPanelEmail1.setLayout(jPanelEmail1Layout);
        jPanelEmail1Layout.setHorizontalGroup(
            jPanelEmail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmail1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWrongEmail1, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
        );
        jPanelEmail1Layout.setVerticalGroup(
            jPanelEmail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmail1Layout.createSequentialGroup()
                .addComponent(jLabelWrongEmail1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelUserName1.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelWrongUserName1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelWrongUserName1.setForeground(java.awt.Color.red);
        jLabelWrongUserName1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelWrongUserName1.setText("Wrong User Name");

        javax.swing.GroupLayout jPanelUserName1Layout = new javax.swing.GroupLayout(jPanelUserName1);
        jPanelUserName1.setLayout(jPanelUserName1Layout);
        jPanelUserName1Layout.setHorizontalGroup(
            jPanelUserName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUserName1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWrongUserName1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
        );
        jPanelUserName1Layout.setVerticalGroup(
            jPanelUserName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUserName1Layout.createSequentialGroup()
                .addComponent(jLabelWrongUserName1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelUrl1.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelWrongURL3.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelWrongURL3.setForeground(java.awt.Color.red);
        jLabelWrongURL3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelWrongURL3.setText("Wrong URL");

        javax.swing.GroupLayout jPanelUrl1Layout = new javax.swing.GroupLayout(jPanelUrl1);
        jPanelUrl1.setLayout(jPanelUrl1Layout);
        jPanelUrl1Layout.setHorizontalGroup(
            jPanelUrl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUrl1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWrongURL3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelUrl1Layout.setVerticalGroup(
            jPanelUrl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUrl1Layout.createSequentialGroup()
                .addComponent(jLabelWrongURL3)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelPass1.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelWrongPass1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelWrongPass1.setForeground(java.awt.Color.red);
        jLabelWrongPass1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelWrongPass1.setText("Wrong Pass");

        javax.swing.GroupLayout jPanelPass1Layout = new javax.swing.GroupLayout(jPanelPass1);
        jPanelPass1.setLayout(jPanelPass1Layout);
        jPanelPass1Layout.setHorizontalGroup(
            jPanelPass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPass1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWrongPass1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
        );
        jPanelPass1Layout.setVerticalGroup(
            jPanelPass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPass1Layout.createSequentialGroup()
                .addComponent(jLabelWrongPass1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelNotAllowed1.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelWrongID3.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelWrongID3.setForeground(java.awt.Color.red);
        jLabelWrongID3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelWrongID3.setText("Not Allowed");

        javax.swing.GroupLayout jPanelNotAllowed1Layout = new javax.swing.GroupLayout(jPanelNotAllowed1);
        jPanelNotAllowed1.setLayout(jPanelNotAllowed1Layout);
        jPanelNotAllowed1Layout.setHorizontalGroup(
            jPanelNotAllowed1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNotAllowed1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWrongID3, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
        );
        jPanelNotAllowed1Layout.setVerticalGroup(
            jPanelNotAllowed1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNotAllowed1Layout.createSequentialGroup()
                .addComponent(jLabelWrongID3)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Reset_96px.png"))); // NOI18N
        jLabelReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelResetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelResetMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelReset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelReset, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
        );

        jPanel1.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelSearch.setBackground(java.awt.SystemColor.controlDkShadow);
        jLabelSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Search_96px.png"))); // NOI18N
        jLabelSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelSearchMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
        );

        jLabel33.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Search");

        jLabel34.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Reset");

        jPanelSearchKey1.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabel55454.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel55454.setForeground(java.awt.Color.red);
        jLabel55454.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabel55454.setText("Wrong Search Key");

        javax.swing.GroupLayout jPanelSearchKey1Layout = new javax.swing.GroupLayout(jPanelSearchKey1);
        jPanelSearchKey1.setLayout(jPanelSearchKey1Layout);
        jPanelSearchKey1Layout.setHorizontalGroup(
            jPanelSearchKey1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSearchKey1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel55454, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelSearchKey1Layout.setVerticalGroup(
            jPanelSearchKey1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSearchKey1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel55454)
                .addGap(5, 5, 5))
        );

        jPanel3.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabel18.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Available_Updates_96px.png"))); // NOI18N
        jLabel18.setText("Update Data");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel18MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel18MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel18)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(jTextFieldAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(293, 293, 293))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldURL1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelUrl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jTextFieldID1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanelID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jPanelSearchKey1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jSeparator12)
                                                    .addComponent(jTextFieldSearchKey1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)
                                        .addComponent(jTextFieldMeterCode1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jPanelMeterCode1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanelNotAllowed1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(85, 85, 85)))
                        .addComponent(jLabelWrongURL2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(203, 203, 203)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(jComboBoxyear1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(jComboBoxmonth1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(jComboBoxday1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(88, 88, 88)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(69, 69, 69)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanelEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldUserName1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanelUserName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldPass1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxGovern1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBoxRagion1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanelPass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabelSuccessOrFail, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelWrongURL2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelSuccessOrFail)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextFieldSearchKey1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3)
                                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelSearchKey1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel34)
                                    .addComponent(jLabel33))))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldMeterCode1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jPanelMeterCode1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanelNotAllowed1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanelID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldID1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldUserName1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanelUserName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jTextFieldPass1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBoxGovern1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jComboBoxRagion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jPanelPass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanelAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldURL1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelUrl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxyear1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxmonth1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxday1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldMeterCode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMeterCode1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMeterCode1ActionPerformed

    private void jComboBoxyear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxyear1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxyear1ActionPerformed

    private void jTextFieldPass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPass1ActionPerformed

    private void jTextFieldAddress1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddress1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAddress1ActionPerformed

    private void jTextFieldURL1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldURL1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldURL1ActionPerformed

    private void jTextFieldUserName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUserName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUserName1ActionPerformed

    private void jComboBoxGovern1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGovern1ActionPerformed
        // TODO add your handling code here:
        if(jComboBoxGovern1.getSelectedItem().equals("Giza"))
            jComboBoxRagion1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Warraq" ,"Agouza","Al Salam","Dokii","El Haram","Imbaba","Zamalek" }));
        else
            jComboBoxRagion1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Old Misr","Rawd Al-Faraj","Nasr City","Downtown Cairo","Ahmed Helmy","Sakakini","Peace","Khalafawi"}));
    }//GEN-LAST:event_jComboBoxGovern1ActionPerformed

    private void jComboBoxRagion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRagion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxRagion1ActionPerformed

    private void jLabelResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelResetMouseClicked
        // TODO add your handling code here:
        jLabelSuccessOrFail.setText("Search Info of Customer ... !");
        resetPanel();

    }//GEN-LAST:event_jLabelResetMouseClicked
    private void setColor(JPanel p)
    {
        p.setBackground(new java.awt.Color(0,64,128));
    }
    private void getColor(JPanel p)
    {
        p.setBackground(new java.awt.Color(105,105,105));
    }
    private void jLabelResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelResetMouseEntered
        // TODO add your handling code here:
        setColor(jPanel2);
    }//GEN-LAST:event_jLabelResetMouseEntered

    private void jLabelResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelResetMouseExited
        // TODO add your handling code here:
        getColor(jPanel2);
    }//GEN-LAST:event_jLabelResetMouseExited

    private void jLabelSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSearchMouseClicked
        // TODO add your handling code here:
        jPanelSearchKey1.setVisible(false);
        jPanelEmail1.setVisible(false);
        jPanelID1.setVisible(false);
        jPanelPass1.setVisible(false);
        jPanelUserName1.setVisible(false);
        jPanelUrl1.setVisible(false);
        jPanelAddress1.setVisible(false);
        jPanelMeterCode1.setVisible(false);
        jPanelNotAllowed1.setVisible(false);
        
        if(!jTextFieldSearchKey1.getText().equals("")){
            if(new Validation().checkID(jTextFieldSearchKey1.getText())){
                Customer t = new Customer();
                Customer x = t.getCustomer(Integer.parseInt(jTextFieldSearchKey1.getText()));
                if(x!=null){
                    setPanel(x);
                    jLabelSuccessOrFail.setText("Founded ...! :)");
                }
                else{
                        jLabelSuccessOrFail.setText("Not Found ...! :(");
                        JOptionPane.showMessageDialog(jLabelSearch, "Not Found Search by Meter Code ...!\n Try Again :(");
                        resetPanel();
                    }
            }
            else{
                JOptionPane.showMessageDialog(jLabelSearch, "Not valid Search by Meter Code Try Again :(\nHint: Search by Meter Code Length should more than 4 .. ;)");
                jPanelSearchKey1.setVisible(true);
            }
        }
        else{
            jLabelSuccessOrFail.setText("Missing Required Meter Code ... ! Please, Complete it to Continue :(");
        }

    }//GEN-LAST:event_jLabelSearchMouseClicked

    private void jLabelSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSearchMouseEntered
        // TODO add your handling code here:
        //setColor(jPanel1);
        setColor(jPanel1);
    }//GEN-LAST:event_jLabelSearchMouseEntered

    private void jLabelSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSearchMouseExited
        // TODO add your handling code here:
        getColor(jPanel1);
    }//GEN-LAST:event_jLabelSearchMouseExited

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
        jPanelSearchKey1.setVisible(false);
        jPanelEmail1.setVisible(false);
        jPanelID1.setVisible(false);
        jPanelPass1.setVisible(false);
        jPanelUserName1.setVisible(false);
        jPanelUrl1.setVisible(false);
        jPanelAddress1.setVisible(false);
        jPanelMeterCode1.setVisible(false);
        jPanelNotAllowed1.setVisible(false);
        
        if(!jTextFieldAddress1.getText().equals("") && !jTextFieldEmail1.getText().equals("") && !jTextFieldID1.getText().equals("") && 
           !jTextFieldMeterCode1.getText().equals("")  && !jTextFieldPass1.getText().equals("") &&
           !jTextFieldSearchKey1.getText().equals("") && !jTextFieldURL1.getText().equals("") &&
           !jTextFieldUserName1.getText().equals(""))
        {
            //All Check ...
            Validation v = new Validation();
            if(v.checkID(jTextFieldSearchKey1.getText())){
                if(v.checkID(jTextFieldID1.getText())){
                        if(v.checkName(jTextFieldUserName1.getText())){
                            if(v.checkPass(jTextFieldPass1.getText())){
                                    if(v.checkEmail(jTextFieldEmail1.getText())){
                                            if(v.checkID(jTextFieldMeterCode1.getText())){
                                                if(v.checkAddress(jTextFieldAddress1.getText())){
                                                    if(v.checkURL(jTextFieldURL1.getText())){

                                                        // End Check :)
                                                        // Start Add
                                                        Customer c = new Customer();
                                                        if(!jTextFieldMeterCode1.getText().equals(jTextFieldSearchKey1.getText())){
                                                            if(!c.Dublicate(Integer.parseInt(jTextFieldMeterCode1.getText()))){
                                                                c.setAddress(jTextFieldAddress1.getText());
                                                                c.setDate(jComboBoxyear1.getSelectedItem().toString()+"#"+jComboBoxmonth1.getSelectedItem().toString()+"#"+jComboBoxday1.getSelectedItem().toString()+"#");
                                                                c.setEmail(jTextFieldEmail1.getText());
                                                                c.setID(Integer.parseInt(jTextFieldID1.getText()));
                                                                c.setMeterCode(Integer.parseInt(jTextFieldMeterCode1.getText()));
                                                                c.setPassword(jTextFieldPass1.getText());
                                                                c.setApartment(jTextFieldURL1.getText());
                                                                c.setUserName(jTextFieldUserName1.getText());
                                                                c.setGovernorate(jComboBoxGovern1.getSelectedItem().toString());
                                                                c.setRegion(jComboBoxRagion1.getSelectedItem().toString());

                                                                    if(c.EditInCustomers(Integer.parseInt(jTextFieldSearchKey1.getText())))
                                                                    {
                                                                        resetPanel();
                                                                        jLabelSuccessOrFail.setText("Updated Successfully ...! :)");
                                                                    }
                                                                    else{
                                                                        jLabelSuccessOrFail.setText("Failed Updated ...! :("); 
                                                                        JOptionPane.showMessageDialog(jLabel18, "Failed Updated ...! :(");
                                                                        jPanelPass1.setVisible(true); 
                                                                         }
                                                                      //End Start & start elses for Check
                                                            }
                                                            
                                                            else{
                                                                    jLabelSuccessOrFail.setText("Not Allowed New ID Customer :(");
                                                                    jPanelNotAllowed1.setVisible(true);
                                                                    JOptionPane.showMessageDialog(jLabel18, "Not Allowed ID Customer , ID Customer is Reserved...!\n Try Again :(");
                                                            }
                                                        }
                                                        else{
                                                                c.setAddress(jTextFieldAddress1.getText());
                                                                c.setDate(jComboBoxyear1.getSelectedItem().toString()+"#"+jComboBoxmonth1.getSelectedItem().toString()+"#"+jComboBoxday1.getSelectedItem().toString()+"#");
                                                                c.setEmail(jTextFieldEmail1.getText());
                                                                c.setID(Integer.parseInt(jTextFieldID1.getText()));
                                                                c.setMeterCode(Integer.parseInt(jTextFieldMeterCode1.getText()));
                                                                c.setPassword(jTextFieldPass1.getText());
                                                                c.setApartment(jTextFieldURL1.getText());
                                                                c.setUserName(jTextFieldUserName1.getText());
                                                                c.setGovernorate(jComboBoxGovern1.getSelectedItem().toString());
                                                                c.setRegion(jComboBoxRagion1.getSelectedItem().toString());

                                                                    if(c.EditInCustomers(Integer.parseInt(jTextFieldSearchKey1.getText())))
                                                                    {
                                                                        resetPanel();
                                                                        jLabelSuccessOrFail.setText("Updated Successfully ...! :)");
                                                                    }
                                                                    else{
                                                                        jLabelSuccessOrFail.setText("Failed Updated ...! :("); 
                                                                        JOptionPane.showMessageDialog(jLabel18, "Failed Updated ...! :(");
                                                                        jPanelPass1.setVisible(true);
                                                                         }
                                                                      //End Start & start elses for Check
                                                        }
                                                    }
                                                    else{
                                                        JOptionPane.showMessageDialog(jLabel18, "Not valid Input for URL Try Again :(");
                                                        jPanelUrl1.setVisible(true);
                                                    }
                                                }
                                                else{
                                                    JOptionPane.showMessageDialog(jLabel18, "Not valid Input for Address Try Again :(");
                                                    jPanelAddress1.setVisible(true);
                                                }
                                            
                                            }
                                            else{
                                                JOptionPane.showMessageDialog(jLabel18, "Not valid Meter Code Try Again :(\nHint: Meter Code Length should more than 4 .. ;)");
                                                jPanelMeterCode1.setVisible(true);
                                            }

                                            

                                    }
                                    else{
                                        JOptionPane.showMessageDialog(jLabel18, "Not valid Input for Email Try Again :(");
                                        jPanelEmail1.setVisible(true);
                                    }

                            }
                            else{
                                JOptionPane.showMessageDialog(jLabel18, "Not valid Password length ,Should it Length\nis more than 6 OR Password has (*,/,=,+,...)\n                    Try Again :(");
                                jPanelPass1.setVisible(true);
                                }
                    }
                        else{
                            JOptionPane.showMessageDialog(jLabel18, "Not valid User Name Try Again :(");
                            jPanelUserName1.setVisible(true);
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(jLabel18, "Not valid ID Try Again :(\nHint: ID Length should more than 4 .. ;)");
                        jPanelID1.setVisible(true);
                    }
            }
            else{
                JOptionPane.showMessageDialog(jLabel18, "Not valid Search by Meter Code Try Again :(\nHint: Search by Meter Code Length should more than 4 .. ;)");
                jPanelSearchKey1.setVisible(true);
            }
        }
        else
        jLabelSuccessOrFail.setText("Missing Required Meter Code ... !  Please, complete it before submit ...! :(");
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseEntered
        // TODO add your handling code here:
        setColor(jPanel3);
    }//GEN-LAST:event_jLabel18MouseEntered

    private void jLabel18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseExited
        // TODO add your handling code here:
        getColor(jPanel3);
    }//GEN-LAST:event_jLabel18MouseExited

    private void jTextFieldEmail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmail1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmail1ActionPerformed
private void setPanel(Customer x )
    {
        jTextFieldAddress1.setText(""+x.getAddress());
        jTextFieldEmail1.setText(""+x.getEmail());
        jTextFieldID1.setText(""+x.getID());
        jTextFieldMeterCode1.setText(""+x.getMeterCode());
        jTextFieldPass1.setText(""+x.getPassword());
        jTextFieldURL1.setText(""+x.getApartment());
        jTextFieldUserName1.setText(""+x.getUserName());
        jComboBoxGovern1.setSelectedItem(x.getGovernorate());
        jComboBoxRagion1.setSelectedItem(x.getRegion());
        String Seprated [] = x.getDate().split("#");
        jComboBoxyear1.setSelectedItem(Seprated[0]);
        jComboBoxmonth1.setSelectedItem(Seprated[1]);
        jComboBoxday1.setSelectedItem(Seprated[2]);
    }private void resetPanel()
    {
        jPanelSearchKey1.setVisible(false);
        jPanelEmail1.setVisible(false);
        jPanelID1.setVisible(false);
        jPanelPass1.setVisible(false);
        jPanelUserName1.setVisible(false);
        jPanelUrl1.setVisible(false);
        jPanelAddress1.setVisible(false);
        jPanelMeterCode1.setVisible(false);
        jPanelNotAllowed1.setVisible(false);
        
        jTextFieldSearchKey1.setText("");
        jTextFieldAddress1.setText("");
        jTextFieldID1.setText("");
        jTextFieldPass1.setText("");
        jTextFieldEmail1.setText("");
        jTextFieldMeterCode1.setText("");
        jTextFieldURL1.setText("");
        jTextFieldUserName1.setText("");
        jComboBoxGovern1.setSelectedIndex(0);
        jComboBoxRagion1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        jComboBoxyear1.setSelectedIndex(0);
        jComboBoxmonth1.setSelectedIndex(0);
        jComboBoxday1.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxGovern1;
    private javax.swing.JComboBox<String> jComboBoxRagion1;
    private javax.swing.JComboBox<String> jComboBoxday1;
    private javax.swing.JComboBox<String> jComboBoxmonth1;
    private javax.swing.JComboBox<String> jComboBoxyear1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel55454;
    private javax.swing.JLabel jLabelReset;
    private javax.swing.JLabel jLabelSearch;
    private javax.swing.JLabel jLabelSuccessOrFail;
    private javax.swing.JLabel jLabelWrongAddress1;
    private javax.swing.JLabel jLabelWrongEmail1;
    private javax.swing.JLabel jLabelWrongID2;
    private javax.swing.JLabel jLabelWrongID3;
    private javax.swing.JLabel jLabelWrongMeterCode1;
    private javax.swing.JLabel jLabelWrongPass1;
    private javax.swing.JLabel jLabelWrongURL2;
    private javax.swing.JLabel jLabelWrongURL3;
    private javax.swing.JLabel jLabelWrongUserName1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelAddress1;
    private javax.swing.JPanel jPanelEmail1;
    private javax.swing.JPanel jPanelID1;
    private javax.swing.JPanel jPanelMeterCode1;
    private javax.swing.JPanel jPanelNotAllowed1;
    private javax.swing.JPanel jPanelPass1;
    private javax.swing.JPanel jPanelSearchKey1;
    private javax.swing.JPanel jPanelUrl1;
    private javax.swing.JPanel jPanelUserName1;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextFieldAddress1;
    private javax.swing.JTextField jTextFieldEmail1;
    private javax.swing.JTextField jTextFieldID1;
    private javax.swing.JTextField jTextFieldMeterCode1;
    private javax.swing.JTextField jTextFieldPass1;
    private javax.swing.JTextField jTextFieldSearchKey1;
    private javax.swing.JTextField jTextFieldURL1;
    private javax.swing.JTextField jTextFieldUserName1;
    // End of variables declaration//GEN-END:variables
}
